confluence_url: https://jatin-bamel.atlassian.net/wiki/rest/api/

confluence_space: testj3
counfluence_parent_page_id: 950287
confluence_search_pattern: (git_release_page)
# github_folder_with_md_files: ./data
# github_folder_with_image_files: ./data_images
