name: Update Confluence on Release

on:
  release:
    types:
      - published

jobs:
  update-confluence:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Update Confluence
      run: |
        python update_confluence.py ${{ secrets.CONFLUENCE_USERNAME }} ${{ secrets.CONFLUENCE_PASSWORD }} \
          ${{ secrets.CONFLUENCE_PAGE_ID }} https://jatin-bamel.atlassian.net/wiki/rest/api/ \
          testj3 131729 ${{ github.event.client_payload.release.tag_name }}
      env:
        CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
        CONFLUENCE_PASSWORD: ${{ secrets.CONFLUENCE_PASSWORD }}
        CONFLUENCE_PAGE_ID: 131729
