name: Update Confluence on Release

on:
  release:
    types:
      - created

jobs:
  update-confluence:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt-get install -y libyaml-dev python3-dev  # Install libyaml and python3 development libraries
          pip install -r ./publisher/requirements.txt


      - name: Update Confluence
        env:
          LOLOGIN: jatsingh9696@gmail.com
          PASSWORD: ATATT3xFfGF0geElBSZ7W09Ye56M6M4Hwhr83opRJo48mifJBx5pPfc5bw_ahFgLxHa0GFoTS1eCaA7eqBowmO9mrYdxlhK4vRovBDGfHdfBkuMMrMCViPYyCEz0eGo-00NZVREfcSfywj1HvJo8mfKREyNIYKB0Akz7KPDVWf1FhMtt3giEiYc=6F694965

        run: |
          python ./publisher/confluence_update_script.py --login="$LOGIN" --password="$PASSWORD"
